# Generated by Django 4.2.1 on 2023-05-09 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzshop', '0002_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pizzshop.type'),
        ),
    ]
